package server

// Contains constant holding Jeedom JSON RPC API

const jeedomObjectDisplayOpts = `{
    "icon": "<i class=\"fa fa-wrench\"></i>",
    "tagColor": "#9b59b6",
    "tagTextColor": "#ffffff",
    "desktop::summaryTextColor": "#000000",
    "dashboard::size": ""
}`

const jeedomDimmerStateCMD = `
{
    "id": "",
    "logicalId": "",
    "eqType_name": "script",
    "name": "state",
    "order": "0",
    "type": "info",
    "subType": "numeric",
    "eqLogic_id": "60",
    "isHistorized": "0",
    "unite": "",
    "configuration": {
        "requestType": "script",
        "request": "#slider#",
        "noSslCheck": "0",
        "allowEmptyResponse": "0",
        "doNotReportHttpError": "0",
        "reponseMustContain": "",
        "timeout": "",
        "maxHttpRetry": "",
        "http_username": "",
        "http_password": "",
        "urlXml": "",
        "xmlNoSslCheck": "0",
        "xmlTimeout": "",
        "maxXmlRetry": "",
        "xml_username": "",
        "xml_password": "",
        "urlHtml": "",
        "htmlNoSslCheck": "0",
        "htmlTimeout": "",
        "maxHtmlRetry": "",
        "html_username": "",
        "html_password": "",
        "urlJson": "",
        "jsonNoSslCheck": "0",
        "jsonTimeout": "",
        "maxJsonRetry": "",
        "json_username": "",
        "json_password": "",
        "minValue": "0",
        "maxValue": "100",
        "updateCmdId": "",
        "updateCmdToValue": "",
        "calculValueOffset": "",
        "historizeRound": "",
        "jeedomCheckCmdOperator": "==",
        "jeedomCheckCmdTest": "",
        "jeedomCheckCmdTime": "",
        "jeedomCheckCmdActionType": "",
        "jeedomCheckCmdCmdActionId": "",
        "jeedomCheckCmdScenarioActionMode": "",
        "jeedomCheckCmdScenarioActionId": "",
        "historizeMode": "avg",
        "historyPurge": "",
        "doNotRepeatEvent": "",
        "jeedomPushUrl": "",
        "value": "",
        "timeline::enable": "0",
        "denyValues": "",
        "returnStateValue": "",
        "returnStateTime": "",
        "repeatEventManagement": "auto",
        "actionCheckCmd": [],
        "jeedomPreExecCmd": [],
        "jeedomPostExecCmd": []
    },
    "template": {
        "dashboard": "light",
        "mobile": "default"
    },
    "display": {
        "icon": "",
        "invertBinary": "0",
        "hideOndashboard": "",
        "hideOnmobile": "",
        "doNotShowNameOnDashboard": "1",
        "doNotShowNameOnView": "",
        "doNotShowStatOnDashboard": "",
        "doNotShowStatOnView": "",
        "doNotShowStatOnMobile": "",
        "forceReturnLineBefore": "0",
        "forceReturnLineAfter": "1",
        "parameters": [],
        "showOncategory": "0",
        "showStatsOncategory": "0",
        "showNameOncategory": "0",
        "showOnstyle": "0",
        "showStatsOnstyle": "0",
        "showNameOnstyle": "0",
        "showNameOndashboard": "0",
        "generic_type": "LIGHT_STATE",
        "showOndashboard": "1",
        "showOnplan": "1",
        "showOnview": "1",
        "showOnmobile": "1",
        "showNameOnplan": "1",
        "showNameOnview": "1",
        "showNameOnmobile": "1",
        "showIconAndNamedashboard": "0",
        "showIconAndNameplan": "0",
        "showIconAndNameview": "0",
        "showIconAndNamemobile": "0"
    },
    "html": {
        "enable": "0",
        "dashboard": "",
        "dview": "",
        "dplan": "",
        "mobile": "",
        "mview": ""
    },
    "value": "",
    "isVisible": "1",
    "alert": {
        "warningif": "",
        "warningduring": "",
        "dangerif": "",
        "dangerduring": ""
    },
    "generic_type": "LIGHT_STATE",
    "currentValue": 0
}`

const jeedomDimmerDimCMD = `
{
    "id": "",
    "logicalId": "",
    "eqType_name": "script",
    "name": "dim",
    "order": "1",
    "type": "action",
    "subType": "slider",
    "eqLogic_id": "",
    "isHistorized": "1",
    "unite": "",
    "configuration": {
        "requestType": "http",
        "request": "http://10.32.2.27:8081/api/v1/jeedom/#eqLogic_id#/#slider#",
        "noSslCheck": "0",
        "allowEmptyResponse": "1",
        "doNotReportHttpError": "1",
        "reponseMustContain": "",
        "timeout": "",
        "maxHttpRetry": "",
        "http_username": "",
        "http_password": "",
        "urlXml": "",
        "xmlNoSslCheck": "0",
        "xmlTimeout": "",
        "maxXmlRetry": "",
        "xml_username": "",
        "xml_password": "",
        "urlHtml": "",
        "htmlNoSslCheck": "0",
        "htmlTimeout": "",
        "maxHtmlRetry": "",
        "html_username": "",
        "html_password": "",
        "urlJson": "",
        "jsonNoSslCheck": "0",
        "jsonTimeout": "",
        "maxJsonRetry": "",
        "json_username": "",
        "json_password": "",
        "minValue": "",
        "maxValue": "",
        "updateCmdId": "",
        "updateCmdToValue": "#slider#",
        "timeline::enable": "0",
        "actionConfirm": "0",
        "actionCodeAccess": "",
        "actionCheckCmd": [],
        "jeedomPreExecCmd": [],
        "jeedomPostExecCmd": []
    },
    "template": {
        "dashboard": "default",
        "mobile": "default"
    },
    "display": {
        "icon": "",
        "invertBinary": "0",
        "generic_type": "",
        "showOndashboard": "1",
        "showOnplan": "1",
        "showOnview": "1",
        "showOnmobile": "1",
        "showNameOndashboard": "0",
        "showNameOnplan": "1",
        "showNameOnview": "1",
        "showNameOnmobile": "1",
        "showIconAndNamedashboard": "0",
        "showIconAndNameplan": "0",
        "showIconAndNameview": "0",
        "showIconAndNamemobile": "0",
        "forceReturnLineBefore": "0",
        "forceReturnLineAfter": "0",
        "parameters": []
    },
    "html": {
        "enable": "0",
        "dashboard": "",
        "dview": "",
        "dplan": "",
        "mobile": "<div class=\"cmd\" data-type=\"action\" data-subtype=\"slider\" data-cmd_id=\"#id#\" data-cmd_uid=\"#uid#\" data-version=\"#version#\">\n\t<div class=\"slider full-width-slider\" style=\"width: 96%;text-align: right;min-width : 100px;\" style=\"background-color:#cmdColor# !important;\">\n\t\t<input type=\"range\" min=\"#minValue#\" max=\"#maxValue#\" data-theme=\"a\" value=\"#state#\" style=\"background-color:#cmdColor# !important;\"/>\n\t</div>\n\t<script>\n\t\t$(\"body\").undelegate(\".cmd[data-cmd_uid=#uid#] .slider\");\n\t\t$(\"body\").delegate(\".cmd[data-cmd_uid=#uid#] .slider\",'slidestop', function (event, ui) {\n\t\t\tjeedom.cmd.execute({id: '#id#', value: {slider: $(\".cmd[data-cmd_uid=#uid#] .slider input\").value()}});\n\t\t});\n\t\tjeedom.cmd.update['#id#'] = function(_options){\n\t\t\t$(\".cmd[data-cmd_id=#id#] .slider input\").value(_options.display_value);\n\t\t}\n\t</script>\n\t<style>\n\t\t.cmd[data-cmd_uid=\"#uid#\"] .ui-slider-handle{\n\t\t\tbackground-color:#cmdColor# !important;\n\t\t}\n\t\t.cmd[data-cmd_uid=\"#uid#\"] .ui-slider-bg{\n\t\t\tbackground-color:#cmdColor# !important;\n\t\t}\n\t</style>\n</div>\n",
        "mview": "<div class=\"cmd\" data-type=\"action\" data-subtype=\"slider\" data-cmd_id=\"#id#\" data-cmd_uid=\"#uid#\" data-version=\"#version#\">\n\t<div class=\"slider full-width-slider\" style=\"width: 96%;text-align: right;min-width : 100px;\" style=\"background-color:#cmdColor# !important;\">\n\t\t<input type=\"range\" min=\"#minValue#\" max=\"#maxValue#\" data-theme=\"a\" value=\"#state#\" style=\"background-color:#cmdColor# !important;\"/>\n\t</div>\n\t<script>\n\t\t$(\"body\").undelegate(\".cmd[data-cmd_uid=#uid#] .slider\");\n\t\t$(\"body\").delegate(\".cmd[data-cmd_uid=#uid#] .slider\",'slidestop', function (event, ui) {\n\t\t\tjeedom.cmd.execute({id: '#id#', value: {slider: $(\".cmd[data-cmd_uid=#uid#] .slider input\").value()}});\n\t\t});\n\t\tjeedom.cmd.update['#id#'] = function(_options){\n\t\t\t$(\".cmd[data-cmd_id=#id#] .slider input\").value(_options.display_value);\n\t\t}\n\t</script>\n\t<style>\n\t\t.cmd[data-cmd_uid=\"#uid#\"] .ui-slider-handle{\n\t\t\tbackground-color:#cmdColor# !important;\n\t\t}\n\t\t.cmd[data-cmd_uid=\"#uid#\"] .ui-slider-bg{\n\t\t\tbackground-color:#cmdColor# !important;\n\t\t}\n\t</style>\n</div>\n"
    },
    "value": "169",
    "isVisible": "1",
    "alert": null,
    "generic_type": "GENERIC_ERROR",
    "currentValue": null
}`

const jeedomDimmerUpdStateCMD = `
{
    "id": "",
    "logicalId": null,
    "eqType_name": "script",
    "name": "updState",
    "order": "2",
    "type": "action",
    "subType": "slider",
    "eqLogic_id": "",
    "isHistorized": "1",
    "unite": "",
    "configuration": {
        "requestType": "script",
        "request": "echo",
        "noSslCheck": "0",
        "allowEmptyResponse": "1",
        "doNotReportHttpError": "0",
        "reponseMustContain": "",
        "timeout": "",
        "maxHttpRetry": "",
        "http_username": "",
        "http_password": "",
        "urlXml": "",
        "xmlNoSslCheck": "0",
        "xmlTimeout": "",
        "maxXmlRetry": "",
        "xml_username": "",
        "xml_password": "",
        "urlHtml": "",
        "htmlNoSslCheck": "0",
        "htmlTimeout": "",
        "maxHtmlRetry": "",
        "html_username": "",
        "html_password": "",
        "urlJson": "",
        "jsonNoSslCheck": "0",
        "jsonTimeout": "",
        "maxJsonRetry": "",
        "json_username": "",
        "json_password": "",
        "minValue": "",
        "maxValue": "",
        "updateCmdId": "",
        "updateCmdToValue": "#slider#"
    },
    "template": null,
    "display": {
        "icon": "",
        "invertBinary": "0"
    },
    "html": null,
    "value": "",
    "isVisible": "0",
    "alert": null,
    "generic_type": "GENERIC_ERROR",
    "currentValue": null
}`

const jeedomSwitchStateCMD = `
{
    "id": "",
    "logicalId": "",
    "eqType_name": "script",
    "name": "state",
    "order": "0",
    "type": "info",
    "subType": "binary",
    "eqLogic_id": "",
    "isHistorized": "0",
    "unite": "",
    "configuration": {
        "requestType": "script",
        "request": "#default#",
        "noSslCheck": "0",
        "allowEmptyResponse": "0",
        "doNotReportHttpError": "0",
        "reponseMustContain": "",
        "timeout": "",
        "maxHttpRetry": "",
        "http_username": "",
        "http_password": "",
        "urlXml": "",
        "xmlNoSslCheck": "0",
        "xmlTimeout": "",
        "maxXmlRetry": "",
        "xml_username": "",
        "xml_password": "",
        "urlHtml": "",
        "htmlNoSslCheck": "0",
        "htmlTimeout": "",
        "maxHtmlRetry": "",
        "html_username": "",
        "html_password": "",
        "urlJson": "",
        "jsonNoSslCheck": "0",
        "jsonTimeout": "",
        "maxJsonRetry": "",
        "json_username": "",
        "json_password": "",
        "minValue": "",
        "maxValue": "",
        "updateCmdId": "",
        "updateCmdToValue": "",
        "timeline::enable": "0",
        "calculValueOffset": "",
        "jeedomCheckCmdOperator": "==",
        "jeedomCheckCmdTest": "",
        "jeedomCheckCmdTime": "",
        "historyPurge": "",
        "denyValues": "",
        "returnStateValue": "",
        "returnStateTime": "",
        "repeatEventManagement": "auto",
        "jeedomPushUrl": "",
        "actionCheckCmd": [],
        "jeedomPreExecCmd": [],
        "jeedomPostExecCmd": []
    },
    "template": {
        "dashboard": "light",
        "mobile": "default"
    },
    "display": {
        "icon": "",
        "invertBinary": "0",
        "generic_type": "",
        "showOndashboard": "1",
        "showOnplan": "1",
        "showOnview": "1",
        "showOnmobile": "1",
        "showNameOndashboard": "0",
        "showNameOnplan": "1",
        "showNameOnview": "1",
        "showNameOnmobile": "1",
        "showIconAndNamedashboard": "0",
        "showIconAndNameplan": "0",
        "showIconAndNameview": "0",
        "showIconAndNamemobile": "0",
        "forceReturnLineBefore": "0",
        "forceReturnLineAfter": "0",
        "parameters": []
    },
    "html": {
        "enable": "0",
        "dashboard": "<div style=\"width:90px;min-height:62px;\" class=\"cmd #history# tooltips cmd-widget\" data-type=\"info\" data-subtype=\"binary\" data-cmd_id=\"#id#\" data-cmd_uid=\"#uid#\" data-version=\"#version#\">\n  <center>\n    <div style=\"font-weight: bold;font-size : 12px;#hideCmdName#\">#name_display#</div>\n     <span style=\"font-size: 2.5em;font-weight: bold;position:relative;top:-6px\" class=\"iconCmd\"></span>\n  </center>\n  <script>\n    jeedom.cmd.update['#id#'] =function(_options){\n      $('.cmd[data-cmd_id=#id#]').attr('title','Valeur du '+_options.valueDate+', collectée le '+_options.collectDate)\n      if (_options.display_value == '1') {\n       $('.cmd[data-cmd_id=#id#] .iconCmd').empty().append('<i class=\"fa fa-check\"></i>');\n     }else {\n      $('.cmd[data-cmd_id=#id#] .iconCmd').empty().append('<i class=\"fa fa-times\"></i>');\n    }\n  }\n  jeedom.cmd.update['#id#']({display_value:'#state#',valueDate:'#valueDate#',collectDate:'#collectDate#',alertLevel:'#alertLevel#'});\n</script>\n</div>",
        "dview": "<div style=\"width:90px;min-height:62px;\" class=\"cmd #history# tooltips cmd-widget\" data-type=\"info\" data-subtype=\"binary\" data-cmd_id=\"#id#\" data-cmd_uid=\"#uid#\" data-version=\"#version#\">\n  <center>\n    <div style=\"font-weight: bold;font-size : 12px;#hideCmdName#\">#name_display#</div>\n     <span style=\"font-size: 2.5em;font-weight: bold;position:relative;top:-6px\" class=\"iconCmd\"></span>\n  </center>\n  <script>\n    jeedom.cmd.update['#id#'] =function(_options){\n      $('.cmd[data-cmd_id=#id#]').attr('title','Valeur du '+_options.valueDate+', collectée le '+_options.collectDate)\n      if (_options.display_value == '1') {\n       $('.cmd[data-cmd_id=#id#] .iconCmd').empty().append('<i class=\"fa fa-check\"></i>');\n     }else {\n      $('.cmd[data-cmd_id=#id#] .iconCmd').empty().append('<i class=\"fa fa-times\"></i>');\n    }\n  }\n  jeedom.cmd.update['#id#']({display_value:'#state#',valueDate:'#valueDate#',collectDate:'#collectDate#',alertLevel:'#alertLevel#'});\n</script>\n</div>",
        "dplan": "<div style=\"width:90px;min-height:62px;\" class=\"cmd #history# tooltips cmd-widget\" data-type=\"info\" data-subtype=\"binary\" data-cmd_id=\"#id#\" data-cmd_uid=\"#uid#\" data-version=\"#version#\">\n  <center>\n    <div style=\"font-weight: bold;font-size : 12px;#hideCmdName#\">#name_display#</div>\n     <span style=\"font-size: 2.5em;font-weight: bold;position:relative;top:-6px\" class=\"iconCmd\"></span>\n  </center>\n  <script>\n    jeedom.cmd.update['#id#'] =function(_options){\n      $('.cmd[data-cmd_id=#id#]').attr('title','Valeur du '+_options.valueDate+', collectée le '+_options.collectDate)\n      if (_options.display_value == '1') {\n       $('.cmd[data-cmd_id=#id#] .iconCmd').empty().append('<i class=\"fa fa-check\"></i>');\n     }else {\n      $('.cmd[data-cmd_id=#id#] .iconCmd').empty().append('<i class=\"fa fa-times\"></i>');\n    }\n  }\n  jeedom.cmd.update['#id#']({display_value:'#state#',valueDate:'#valueDate#',collectDate:'#collectDate#',alertLevel:'#alertLevel#'});\n</script>\n</div>",
        "mobile": "",
        "mview": ""
    },
    "value": "",
    "isVisible": "1",
    "alert": {
        "warningif": "",
        "warningduring": "",
        "dangerif": "",
        "dangerduring": ""
    },
    "generic_type": "GENERIC_ERROR",
    "currentValue": 0
}
`
const jeedomSwitchOnOffCMD = `
{
    "id": "",
    "logicalId": null,
    "eqType_name": "script",
    "name": "on",
    "order": "1",
    "type": "action",
    "subType": "other",
    "eqLogic_id": "",
    "isHistorized": "1",
    "unite": "",
    "configuration": {
        "requestType": "http",
        "request": "",
        "noSslCheck": "0",
        "allowEmptyResponse": "1",
        "doNotReportHttpError": "1",
        "reponseMustContain": "",
        "timeout": "",
        "maxHttpRetry": "",
        "http_username": "",
        "http_password": "",
        "urlXml": "",
        "xmlNoSslCheck": "0",
        "xmlTimeout": "",
        "maxXmlRetry": "",
        "xml_username": "",
        "xml_password": "",
        "urlHtml": "",
        "htmlNoSslCheck": "0",
        "htmlTimeout": "",
        "maxHtmlRetry": "",
        "html_username": "",
        "html_password": "",
        "urlJson": "",
        "jsonNoSslCheck": "0",
        "jsonTimeout": "",
        "maxJsonRetry": "",
        "json_username": "",
        "json_password": "",
        "minValue": "",
        "maxValue": "",
        "updateCmdId": "189",
        "updateCmdToValue": "100"
    },
    "template": null,
    "display": {
        "icon": "",
        "invertBinary": "0"
    },
    "html": null,
    "value": "189",
    "isVisible": "1",
    "alert": null,
    "generic_type": "GENERIC_ERROR",
    "currentValue": null
}`

const jeedomSwitchUpdStateCMD = `
{
    "id": "",
    "logicalId": null,
    "eqType_name": "script",
    "name": "updState",
    "order": "3",
    "type": "action",
    "subType": "slider",
    "eqLogic_id": "",
    "isHistorized": "1",
    "unite": "",
    "configuration": {
        "requestType": "script",
        "request": "echo",
        "noSslCheck": "0",
        "allowEmptyResponse": "0",
        "doNotReportHttpError": "0",
        "reponseMustContain": "",
        "timeout": "",
        "maxHttpRetry": "",
        "http_username": "",
        "http_password": "",
        "urlXml": "",
        "xmlNoSslCheck": "0",
        "xmlTimeout": "",
        "maxXmlRetry": "",
        "xml_username": "",
        "xml_password": "",
        "urlHtml": "",
        "htmlNoSslCheck": "0",
        "htmlTimeout": "",
        "maxHtmlRetry": "",
        "html_username": "",
        "html_password": "",
        "urlJson": "",
        "jsonNoSslCheck": "0",
        "jsonTimeout": "",
        "maxJsonRetry": "",
        "json_username": "",
        "json_password": "",
        "minValue": "",
        "maxValue": "",
        "updateCmdId": "89",
        "updateCmdToValue": "#slider#"
    },
    "template": null,
    "display": {
        "icon": "",
        "invertBinary": "0"
    },
    "html": null,
    "value": "",
    "isVisible": "0",
    "alert": null,
    "generic_type": "GENERIC_ERROR",
    "currentValue": null
}`
